### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by Mark-Sellwood** [imcfarla2003/domoticz-hive#11]
Yesterday MONIT restarted my production system as domoticz had stopped responding.
Looking at the memory usage I can see that it started to increase on the 21 January, also the following errors stated to appear in the log:-
`2019-01-27 07:59:47.950 Error: (Hive) 'onHeartbeat' failed 'KeyError'.`
`2019-01-27 07:59:47.950 Error: (Hive) ----> Line 594 in /home/pi/domoticz/plugins/Hive/plugin.py, function onHeartbeat`
`2019-01-27 07:59:47.950 Error: (Hive) ----> Line 250 in /home/pi/domoticz/plugins/Hive/plugin.py, function onHeartbeat`
![memory production](https://user-images.githubusercontent.com/46023933/51798707-e1853200-220e-11e9-9433-59c4e21e223e.JPG)

So i had a play on my test system, I did a git pull on the plugin, I disabled all plugins with the exception of this one, rebooted the Pi.
At 9AM the memory used was 12%, at 9PM the memory used had increased to 56% so i stopped the Hive plugin, this morning the memory is at 57%.
![memory test](https://user-images.githubusercontent.com/46023933/51798744-65d7b500-220f-11e9-8d37-fad6419146a4.JPG)
Also see the following in the log
`2019-01-26 21:11:24.097 Error: (Hive): Async Secure Read Exception: 1, stream truncated`
`2019-01-26 21:11:25.769 Error: (Hive) 'onMessage' failed 'KeyError'.`
`2019-01-26 21:11:25.769 Error: (Hive) ----> Line 860 in '/home/pi/domoticz/plugins/domoticz-hive/plugin.py', function onMessage`
`2019-01-26 21:11:25.769 Error: (Hive) ----> Line 155 in '/home/pi/domoticz/plugins/domoticz-hive/plugin.py', function onMessage`
`2019-01-26 21:11:25.769 Error: (Hive) ----> Line 481 in '/home/pi/domoticz/plugins/domoticz-hive/plugin.py', function UpdateDeviceState`
`2019-01-26 21:11:25.771 Error: (Hive): Async Secure Read Exception: 1, stream truncated`

I have attached the output from collect_json.py
[collect_json.py.txt.txt](https://github.com/imcfarla2003/domoticz-hive/files/2799872/collect_json.py.txt.txt)
Production
Domoticz V4.9700
Python version 3.5.3

Test
Domoticz V4.10365
Python version '3.5.3

**Comment by ad5trett** [comment]
Though I didn’t check memory usage, a similar thing with Monit restarting my system was the first clue to there being a problem with the latest plugin for me.

**Comment by imcfarla2003** [comment]
Can you try with the latest version please?

**Comment by imcfarla2003** [comment]
I think when the session had failed multiple connections were being created but not removed.
This has hopefully been addressed.
