### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Calzor-Suzay** [imcfarla2003/domoticz-hive#12]
In my log I see the following error every minute.
It all 'seems' to work just have errors.
Running v1 on Domoticz beta 4.10445

2019-02-25 12:22:30.577 Error: CConnection_connect, connect request from 'Hive1' ignored. Transport is connected.
2019-02-25 12:22:31.014 Error: (Hive1): Async Secure Read Exception: 1, stream truncated

**Comment by Mark-Sellwood** [comment]
Keep an eye on the memory usage, this plugin consumed all the free memory, after this Domoticz became unresponsive & I had to reboot the Pi.

**Comment by Calzor-Suzay** [comment]
So far it's been fine but I'm on a Vero4k on OSMC not a Pi although my old Pi I use to run OSMC on.

**Comment by imcfarla2003** [comment]
This is not an error with the plugin but with domoticz itself.  It has the transport functionality built-in which we then use with the plugin.
