### ISSUE TITLE
Plugin fails to run 'AttributeError':''bool' object has no attribute 'Connect''

### ISSUE THREAD

**Issue by peteralm097** [imcfarla2003/domoticz-hive#15]
2020-05-20 15:32:44.512 Error: (domoticz-hive) 'onHeartbeat' failed 'AttributeError':''bool' object has no attribute 'Connect''.
2020-05-20 15:32:44.512 Error: (domoticz-hive) ----> Line 886 in '/home/pi/domoticz/plugins/domoticz-hive/plugin.py', function onHeartbeat
2020-05-20 15:32:44.512 Error: (domoticz-hive) ----> Line 224 in '/home/pi/domoticz/plugins/domoticz-hive/plugin.py', function onHeartbeat

This is on the latest version from github and the 2020.2 version of domoticz RPI
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

**Comment by peteralm097** [comment]
Removing lines 86-88 and re-indenting (I know what version I am running!) have done the trick - this must have been an error that came in when the version numbering changed in Demoticz.

**Comment by russdan** [comment]
I've reworked the getDomoticzRevision function to parse out "new" 2020.2 build numbers which is the alternative to removing lines 86-88:

```
diff --git a/plugin.py b/plugin.py
index 5d16d70..91af944 100644
--- a/plugin.py
+++ b/plugin.py
@@ -792,8 +792,21 @@ class BasePlugin:
     def getDomoticzRevision(self):
         Revision = 8650 #Min version that supports all the features required -1
         if 'DomoticzVersion' in Parameters:
-            Domoticz.Log("DomoticzVersion Available")
-            Revision = Parameters['DomoticzVersion'].split(".")[1]
+            Domoticz.Log("DomoticzVersion Available" + Parameters['DomoticzVersion'])
+
+            # New version numbering for 2020.2 builds - check and parse accordingly
+
+            Revision = Parameters['DomoticzVersion']
+
+            newBuild = Revision.find('2020.2')
+            if newBuild == -1:
+                Domoticz.Log("Pre-2020.2 build found")
+                Revision = Parameters['DomoticzVersion'].split(".")[1]
+            else:
+                Domoticz.Log("Post-2020.2 build found")
+                Revision = Parameters['DomoticzVersion'].split("(build ")[1]
+                Revision = Revision.rstrip(')')
+
         Domoticz.Debug("Domoticz Revision: " + str(Revision))
         return Revision

```
@imcfarla2003 can this be pushed to the latest code please?

**Comment by imcfarla2003** [comment]
Applied
