### ISSUE TITLE
Hive endpoint and message format changed (completely!)

### ISSUE THREAD

**Issue by russdan** [imcfarla2003/domoticz-hive#18]
Hi @imcfarla2003 , you're probably aware but last week BG have changed the endpoint and message format so login response gives a response of:

`"genericError":{"error": {"reason":"GONE","message":"Not.supported.anymore"}}}"`

there's a Domoticz thread which has some pointers:

[https://www.domoticz.com/forum/viewtopic.php?f=38&t=6837&sid=3daa3dee81ffdd092e9cca68f4de922a&start=240](https://www.domoticz.com/forum/viewtopic.php?f=38&t=6837&sid=3daa3dee81ffdd092e9cca68f4de922a&start=240)

 and these two are very helpful also:

[https://github.com/alyc100/SmartThingsPublic/blob/master/smartapps/alyc100/hive-connect.src/hive-connect.groovy]( https://github.com/alyc100/SmartThingsPublic/blob/master/smartapps/alyc100/hive-connect.src/hive-connect.groovy )and
[https://jedkirby.com/blog/hive-home-rest-api](https://jedkirby.com/blog/hive-home-rest-api)

which have helped a lot to the point I have my own standalone code which handles hotwater boost now able to log in and retrieve nodes, but the changes to the messages are extensive (although not too hard to fathom)!  I don't have any plugs or light switches so can't test those although the jedkirby blog shows activating switches - I hope to have my own code working today for hotwater relay state/boost and reading thermostat temperature which I'll then look at whether I can re-incorporate what I know back into the plugin.

If its of any help, here's where I am so far with login:
```
def HiveLogin():
    postheaders = {'Content-Type': 'application/json',
        'Accept': 'application/json',
        'devices' : 'true',
        'products' : 'true',
        'actions' : 'true',
        'homes' : 'true',
        'X-Omnia-Client': 'Hive Web Dashboard'}

    hostname = 'https://beekeeper.hivehome.com/1.0/cognito/login'
    postbody = {'username': hiveuser, 'password': hivepass}
    payld = json.dumps(postbody)
    response = requests.post(hostname,headers=postheaders,data=payld)
    data = response.json()
    sessionID = data["token"]
    return sessionID
```
and "device" (now "products") list (apologies for the while node <3, I haven't written a better way yet of doing this!)

```
hostname = 'https://beekeeper-uk.hivehome.com/1.0/products'
getheaders = {'Content-Type': 'application/json',
'Accept': 'application/json',
'authorization': sessionID}
response = requests.get(hostname,headers=getheaders)
if response.status_code == 200:
    login_successful = True
    DomoticzMessage("Hive Hotwaterboost: Session ID: " + sessionID)
    data = response.json()
    node = 0
    while node < 3:
        try:
            if data[node]["type"] == "hotwater":
                receiverID = data[node]["id"]
                DomoticzMessage("Hive Hotwaterboost: Found Hotwater receiver at: " + receiverID)
                break
            else:
                node = node + 1
        except:
            node = node + 1
    break
```
Here's the response from https://beekeeper-uk.hivehome.com/1.0/products  which you can see is completely different to the old response, in format, and number of nodes (I only see 'heating' and 'hotwater' now instead of the 7 nodes before):
```
[
    {
        "id": "bad89169-f7e2-494b-8f85-3f9xxxxxxxx8",
        "type": "heating",
        "sortOrder": 1,
        "created": 1489926135292,
        "lastSeen": 1600084128533,
        "parent": "477b36ee-6c9c-47c5-b1d0-a80xxxxxxxxxxx",
        "props": {
            "online": true,
            "model": "SLR2",
            "version": "10094640",
            "upgrade": {
                "available": false,
                "upgrading": false
            },
            "capabilities": [
                "INFORMATION",
                "RENAME",
                "HEATING_ALERTS",
                "GEOLOCATION",
                "HOLIDAY_MODE",
                "BOOST",
                "OPTIMUM_START"
            ],
            "holidayMode": {
                "active": false,
                "enabled": false,
                "start": null,
                "end": null,
                "temperature": 7
            },
            "modelVariant": "SLR2",
            "working": false,
            "pmz": "OK",
            "previous": {
                "mode": "SCHEDULE"
            },
            "scheduleOverride": false,
            "temperature": 21.1,
            "zone": "477b36ee-6c9c-47c5-b1d0-a80xxxxxxxxxxx",
            "autoBoost": {
                "active": false,
                "target": 22,
                "duration": 30,
                "trvs": []
            },
            "readyBy": false
        },
        "state": {
            "name": "Receiver",
            "boost": null,
            "frostProtection": 7,
            "mode": "SCHEDULE",
            "schedule": {
                "monday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "tuesday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "wednesday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "thursday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "friday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "saturday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "sunday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ]
            },
            "target": 12,
            "optimumStart": false,
            "autoBoost": "DISABLED",
            "autoBoostTarget": 22
        }
    },
    {
        "id": "cbd60e1d-c3fb-41a8-a52f-547xxxxxxxx2",
        "type": "hotwater",
        "sortOrder": 2,
        "created": 1489926137117,
        "lastSeen": 1600084128533,
        "parent": "477b36ee-6c9c-47c5-b1d0-a80xxxxxxa",
        "props": {
            "online": true,
            "model": "SLR2",
            "version": "10094640",
            "upgrade": {
                "available": false,
                "upgrading": false
            },
            "modelVariant": "SLR2",
            "zone": "477b36ee-6c9c-47c5-b1d0-a80xxxxxxa",
            "working": false,
            "holidayMode": {
                "active": false,
                "enabled": false,
                "start": null,
                "end": null
            },
            "capabilities": [
                "INFORMATION",
                "HOLIDAY_MODE",
                "BOOST"
            ],
            "previous": {
                "mode": "SCHEDULE"
            },
            "pmz": "OK"
        },
        "state": {
            "name": "Receiver",
            "mode": "SCHEDULE",
            "schedule": {
                "monday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "tuesday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "wednesday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "thursday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "friday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "saturday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "sunday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ]
            },
            "boost": null,
            "status": "OFF"
        }
    }
]
```

I can't see now, for example, where weather comes from, but my priority today is getting my automatic hotwater boost working again (I have a DS18B20-based system which feeds the hotwater level and temp in my tank so can auto-boost if the level drops below a certain temp and/or level).  When I get this going I'll see if I can start on the plugin code too - would you be happy to give me the ability to contribute any changes I make into a new branch?

I guess this was always on the cards that BG could randomly and without warning change the api at some stage!

**Comment by imcfarla2003** [comment]
Feel free to fork and create pull requests.I don't use the heating side anymore ( and never used the hot water functions)The more people we have working on the plugin the better is my view.On 4 Oct 2020 07:52, russdan <notifications@github.com> wrote:
Hi @imcfarla2003 , you're probably aware but last week BG have changed the endpoint and message format so login response gives a response of:
"genericError":{"error": {"reason":"GONE","message":"Not.supported.anymore"}}}"
there's a Domoticz thread which has some pointers:
https://www.domoticz.com/forum/viewtopic.php?f=38&t=6837&sid=3daa3dee81ffdd092e9cca68f4de922a&start=240
and these two are very helpful also:
https://github.com/alyc100/SmartThingsPublic/blob/master/smartapps/alyc100/hive-connect.src/hive-connect.groovyand
https://jedkirby.com/blog/hive-home-rest-api
which have helped a lot to the point I have my own standalone code which handles hotwater boost now able to log in and retrieve nodes, but the changes to the messages are extensive (although not too hard to fathom)!  I don't have any plugs or light switches so can't test those although the jedkirby blog shows activating switches - I hope to have my own code working today for hotwater relay state/boost and reading thermostat temperature which I'll then look at whether I can re-incorporate what I know back into the plugin.
If its of any help, here's where I am so far with login:
def HiveLogin():
    postheaders = {'Content-Type': 'application/json',
        'Accept': 'application/json',
        'devices' : 'true',
        'products' : 'true',
        'actions' : 'true',
        'homes' : 'true',
        'X-Omnia-Client': 'Hive Web Dashboard'}

    hostname = 'https://beekeeper.hivehome.com/1.0/cognito/login'
    postbody = {'username': hiveuser, 'password': hivepass}
    payld = json.dumps(postbody)
    response = requests.post(hostname,headers=postheaders,data=payld)
    data = response.json()
    sessionID = data["token"]
    return sessionID

and "device" (now "products") list (apologies for the while node <3, I haven't written a better way yet of doing this!)
hostname = 'https://beekeeper-uk.hivehome.com/1.0/products'
getheaders = {'Content-Type': 'application/json',
'Accept': 'application/json',
'authorization': sessionID}
response = requests.get(hostname,headers=getheaders)
if response.status_code == 200:
    login_successful = True
    DomoticzMessage("Hive Hotwaterboost: Session ID: " + sessionID)
    data = response.json()
    node = 0
    while node < 3:
        try:
            if data[node]["type"] == "hotwater":
                receiverID = data[node]["id"]
                DomoticzMessage("Hive Hotwaterboost: Found Hotwater receiver at: " + receiverID)
                break
            else:
                node = node + 1
        except:
            node = node + 1
    break

Here's the response from https://beekeeper-uk.hivehome.com/1.0/products  which you can see is completely different to the old response, in format, and number of nodes (I only see 'heating' and 'hotwater' now instead of the 7 nodes before):
[
    {
        "id": "bad89169-f7e2-494b-8f85-3f9xxxxxxxx8",
        "type": "heating",
        "sortOrder": 1,
        "created": 1489926135292,
        "lastSeen": 1600084128533,
        "parent": "477b36ee-6c9c-47c5-b1d0-a80xxxxxxxxxxx",
        "props": {
            "online": true,
            "model": "SLR2",
            "version": "10094640",
            "upgrade": {
                "available": false,
                "upgrading": false
            },
            "capabilities": [
                "INFORMATION",
                "RENAME",
                "HEATING_ALERTS",
                "GEOLOCATION",
                "HOLIDAY_MODE",
                "BOOST",
                "OPTIMUM_START"
            ],
            "holidayMode": {
                "active": false,
                "enabled": false,
                "start": null,
                "end": null,
                "temperature": 7
            },
            "modelVariant": "SLR2",
            "working": false,
            "pmz": "OK",
            "previous": {
                "mode": "SCHEDULE"
            },
            "scheduleOverride": false,
            "temperature": 21.1,
            "zone": "477b36ee-6c9c-47c5-b1d0-a80xxxxxxxxxxx",
            "autoBoost": {
                "active": false,
                "target": 22,
                "duration": 30,
                "trvs": []
            },
            "readyBy": false
        },
        "state": {
            "name": "Receiver",
            "boost": null,
            "frostProtection": 7,
            "mode": "SCHEDULE",
            "schedule": {
                "monday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "tuesday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "wednesday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "thursday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "friday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "saturday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ],
                "sunday": [
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 360
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 510
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1020
                    },
                    {
                        "value": {
                            "target": 12
                        },
                        "start": 1320
                    }
                ]
            },
            "target": 12,
            "optimumStart": false,
            "autoBoost": "DISABLED",
            "autoBoostTarget": 22
        }
    },
    {
        "id": "cbd60e1d-c3fb-41a8-a52f-547xxxxxxxx2",
        "type": "hotwater",
        "sortOrder": 2,
        "created": 1489926137117,
        "lastSeen": 1600084128533,
        "parent": "477b36ee-6c9c-47c5-b1d0-a80xxxxxxa",
        "props": {
            "online": true,
            "model": "SLR2",
            "version": "10094640",
            "upgrade": {
                "available": false,
                "upgrading": false
            },
            "modelVariant": "SLR2",
            "zone": "477b36ee-6c9c-47c5-b1d0-a80xxxxxxa",
            "working": false,
            "holidayMode": {
                "active": false,
                "enabled": false,
                "start": null,
                "end": null
            },
            "capabilities": [
                "INFORMATION",
                "HOLIDAY_MODE",
                "BOOST"
            ],
            "previous": {
                "mode": "SCHEDULE"
            },
            "pmz": "OK"
        },
        "state": {
            "name": "Receiver",
            "mode": "SCHEDULE",
            "schedule": {
                "monday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "tuesday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "wednesday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "thursday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "friday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "saturday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ],
                "sunday": [
                    {
                        "value": {
                            "status": "ON"
                        },
                        "start": 300
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 345
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 720
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 840
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 960
                    },
                    {
                        "value": {
                            "status": "OFF"
                        },
                        "start": 990
                    }
                ]
            },
            "boost": null,
            "status": "OFF"
        }
    }
]

I can't see now, for example, where weather comes from, but my priority today is getting my automatic hotwater boost working again (I have a DS18B20-based system which feeds the hotwater level and temp in my tank so can auto-boost if the level drops below a certain temp and/or level).  When I get this going I'll see if I can start on the plugin code too - would you be happy to give me the ability to contribute any changes I make into a new branch?
I guess this was always on the cards that BG could randomly and without warning change the api at some stage!
